# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sniffer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(3045, 1957)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(220, 140, 2741, 821))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidgetGateway = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.tableWidgetGateway.setAutoScroll(False)
        self.tableWidgetGateway.setObjectName("tableWidgetGateway")
        self.tableWidgetGateway.setColumnCount(0)
        self.tableWidgetGateway.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidgetGateway)
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 50, 271, 61))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1620, 50, 271, 61))
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(220, 1050, 2741, 821))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidgetIsolatedGateway = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        self.tableWidgetIsolatedGateway.setAutoScroll(False)
        self.tableWidgetIsolatedGateway.setObjectName("tableWidgetIsolatedGateway")
        self.tableWidgetIsolatedGateway.setColumnCount(0)
        self.tableWidgetIsolatedGateway.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tableWidgetIsolatedGateway)
        self.tableWidgetIsolatedCAN = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        self.tableWidgetIsolatedCAN.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidgetIsolatedCAN.setAutoScroll(False)
        self.tableWidgetIsolatedCAN.setObjectName("tableWidgetIsolatedCAN")
        self.tableWidgetIsolatedCAN.setColumnCount(0)
        self.tableWidgetIsolatedCAN.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tableWidgetIsolatedCAN)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 3045, 39))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "GATEWAY TABLE"))
        self.label_2.setText(_translate("MainWindow", "CAN TABLE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
